FROM python:3

RUN git clone https://github.com/NicoBeast98/um-programacion-i-2020.git

WORKDIR /um-programacion-i-2020/58032-Aldeco,Nicolas/tp3

RUN pip install -r requirements.txt

CMD ["python3", "test_cajero.py"]